// Mock data for cinemas
export const mockCinemas = [
  {
    id: 1,
    name: "CGV Vincom Center",
    address: "Số 72 Lê Thánh Tôn, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh",
    screenCount: 8,
    status: "active",
    phone: "028 3827 9999",
    email: "info.cgvvincom@cgv.vn",
  },
  {
    id: 2,
    name: "Galaxy Nguyễn Du",
    address: "116 Nguyễn Du, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh",
    screenCount: 5,
    status: "active",
    phone: "028 3822 8888",
    email: "info.galaxyndu@galaxy.vn",
  },
  {
    id: 3,
    name: "Lotte Cinema Nowzone",
    address: "235 Nguyễn Văn Cừ, Phường Nguyễn Cư Trinh, Quận 1, TP. Hồ Chí Minh",
    screenCount: 6,
    status: "active",
    phone: "028 3926 2222",
    email: "info.lottenowzone@lotte.vn",
  },
  {
    id: 4,
    name: "BHD Star Bitexco",
    address: "Tầng 3, TTTM Icon 68, 2 Hải Triều, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh",
    screenCount: 5,
    status: "active",
    phone: "028 3823 7777",
    email: "info.bhdbitexco@bhd.vn",
  },
  {
    id: 5,
    name: "CGV Aeon Mall Tân Phú",
    address: "30 Bờ Bao Tân Thắng, Phường Sơn Kỳ, Quận Tân Phú, TP. Hồ Chí Minh",
    screenCount: 7,
    status: "maintenance",
    phone: "028 3849 3333",
    email: "info.cgvaeon@cgv.vn",
  },
]

// Mock data for screens
export const mockScreens = [
  {
    id: 1,
    cinemaId: 1,
    name: "Screen 1",
    capacity: 120,
    type: "2d",
    status: "active",
  },
  {
    id: 2,
    cinemaId: 1,
    name: "Screen 2",
    capacity: 150,
    type: "3d",
    status: "active",
  },
  {
    id: 3,
    cinemaId: 1,
    name: "Screen 3",
    capacity: 180,
    type: "imax",
    status: "active",
  },
  {
    id: 4,
    cinemaId: 1,
    name: "Screen 4",
    capacity: 100,
    type: "2d",
    status: "maintenance",
  },
  {
    id: 5,
    cinemaId: 2,
    name: "Screen 1",
    capacity: 130,
    type: "2d",
    status: "active",
  },
  {
    id: 6,
    cinemaId: 2,
    name: "Screen 2",
    capacity: 140,
    type: "3d",
    status: "active",
  },
]

// Mock data for movies
export const mockMovies = [
  {
    id: 1,
    title: "Avengers: Endgame",
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    duration: 181,
    genre: "Action, Adventure, Drama",
    director: "Anthony Russo, Joe Russo",
    cast: "Robert Downey Jr., Chris Evans, Mark Ruffalo",
    releaseDate: "2019-04-26",
    status: "showing",
    posterUrl: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 2,
    title: "Joker",
    description:
      "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.",
    duration: 122,
    genre: "Crime, Drama, Thriller",
    director: "Todd Phillips",
    cast: "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
    releaseDate: "2019-10-04",
    status: "showing",
    posterUrl: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 3,
    title: "Parasite",
    description:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    duration: 132,
    genre: "Comedy, Drama, Thriller",
    director: "Bong Joon Ho",
    cast: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
    releaseDate: "2019-11-08",
    status: "showing",
    posterUrl: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 4,
    title: "The Dark Knight",
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    duration: 152,
    genre: "Action, Crime, Drama",
    director: "Christopher Nolan",
    cast: "Christian Bale, Heath Ledger, Aaron Eckhart",
    releaseDate: "2008-07-18",
    status: "showing",
    posterUrl: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 5,
    title: "Inception",
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    duration: 148,
    genre: "Action, Adventure, Sci-Fi",
    director: "Christopher Nolan",
    cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
    releaseDate: "2010-07-16",
    status: "showing",
    posterUrl: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 6,
    title: "Dune",
    description:
      "Feature adaptation of Frank Herbert's science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.",
    duration: 155,
    genre: "Adventure, Drama, Sci-Fi",
    director: "Denis Villeneuve",
    cast: "Timothée Chalamet, Rebecca Ferguson, Zendaya",
    releaseDate: "2021-10-22",
    status: "coming_soon",
    posterUrl: "/placeholder.svg?height=300&width=200",
  },
]

// Mock data for showtimes
export const mockShowtimes = [
  {
    id: 1,
    movieId: 1,
    cinemaId: 1,
    screenId: 1,
    startTime: "2023-04-23T10:00:00",
    endTime: "2023-04-23T13:01:00",
    price: 120000,
    availableSeats: 100,
  },
  {
    id: 2,
    movieId: 1,
    cinemaId: 1,
    screenId: 1,
    startTime: "2023-04-23T14:00:00",
    endTime: "2023-04-23T17:01:00",
    price: 150000,
    availableSeats: 95,
  },
  {
    id: 3,
    movieId: 2,
    cinemaId: 1,
    screenId: 2,
    startTime: "2023-04-23T11:30:00",
    endTime: "2023-04-23T13:32:00",
    price: 130000,
    availableSeats: 120,
  },
  {
    id: 4,
    movieId: 3,
    cinemaId: 1,
    screenId: 3,
    startTime: "2023-04-23T15:00:00",
    endTime: "2023-04-23T17:12:00",
    price: 180000,
    availableSeats: 150,
  },
  {
    id: 5,
    movieId: 4,
    cinemaId: 2,
    screenId: 5,
    startTime: "2023-04-23T10:30:00",
    endTime: "2023-04-23T13:02:00",
    price: 120000,
    availableSeats: 110,
  },
  {
    id: 6,
    movieId: 5,
    cinemaId: 2,
    screenId: 6,
    startTime: "2023-04-23T14:30:00",
    endTime: "2023-04-23T16:58:00",
    price: 140000,
    availableSeats: 125,
  },
]

// Mock data for users
export const mockUsers = [
  {
    id: 1,
    name: "Nguyễn Văn Admin",
    email: "admin@example.com",
    phone: "0901234567",
    role: "admin",
    status: "active",
  },
  {
    id: 2,
    name: "Trần Thị Staff",
    email: "staff@example.com",
    phone: "0912345678",
    role: "staff",
    status: "active",
  },
  {
    id: 3,
    name: "Lê Văn Customer",
    email: "customer1@example.com",
    phone: "0923456789",
    role: "customer",
    status: "active",
  },
  {
    id: 4,
    name: "Phạm Thị User",
    email: "customer2@example.com",
    phone: "0934567890",
    role: "customer",
    status: "active",
  },
  {
    id: 5,
    name: "Hoàng Văn Blocked",
    email: "blocked@example.com",
    phone: "0945678901",
    role: "customer",
    status: "blocked",
  },
]
